


function Add-SvgBackground
{
  <#
      .SYNOPSIS
      Takes path to a SVG file (created by KiCAD) and adds a solid-color background

      .DESCRIPTION
      This function was written to specifically process SVG image files generated by KiCAD
      It assumes that the second line contains the title and the third line contains a description, and that there is a "viewport" defined in the root node
      It then reads the viewport settings from the root element, and replaces the third line (originally holding the description)
      with a rectangle statement covering the entire viewport
      In addition, the title is changed to the pure file name (without extension)

      As-is, it works for KiCAD-generated SVGs only.
      If you'd like to extend it to any SVG, you would have to modify it. 

      .EXAMPLE
      Add-SvgBackground 
      Adds a white background to a SVG file, and saves it as a new file with filename suffix '_w'
      This assumes the SVG file path was copied to the clipboard prior to calling this function:
      (hold SHIFT, then right-click a SVG file in Windows Explorer, then choose "Copy as path" in the context menu) 

      .EXAMPLE
      Add-SvgBackground -Path c:\temp\test.svg -Suffix '' -BackgroundColor Green -OpenFile
      Adds a green background to a SVG file, and updates it. No new file is created. The original file is changed.
      After the change, the file is opened in the default app.

      .EXAMPLE
      Add-SvgBackground -BackgroundColor FFAA76 -Suffix '_new'
      Adds a self-defined RGB background color to a SVG file, and saves it as a new file with filename suffix '_new'
      (assuming the SVG file path was copied to the clipboard prior to calling this function)
    
      .EXAMPLE
      Add-SvgBackground -BackgroundColor FFAA7640 -Suffix '_new'
      Adds a self-defined RGB background color to a SVG file and sets its transparency to 25% (value 64, hex value '40'), and saves it as a new file with filename suffix '_new'
      (assuming the SVG file path was copied to the clipboard prior to calling this function)
  #>


  # add a white background to a svg
  
  [CmdletBinding(DefaultParameterSetName='DefaultColors')]
  param
  (
    # path to existing SVG file
    # if not specified, default value is taken from clipboard
    [string]$Path = $(
    
      $temp = (Get-Clipboard).Trim('" ')
      $exists = Test-Path -Path $temp -PathType Leaf
      if (!$exists)
      {
        throw "You must specify the path to a SVG file or make sure a valid path was copied to the clipboard.`r`n'$temp' is no valid path or does not exist."
      }
      $temp
            
    ),
    
    # desired background color, can also be a hex RGB code
    [Parameter(ParameterSetName='StringColors', Position=1)]
    [string]$BackgroundColor = 'White',
    
    [Parameter(ParameterSetName='RGBColors', Position = 1)]
    [byte]$Red = 255,
    [Parameter(ParameterSetName='RGBColors', Position = 2)]
    [byte]$Green = 255,
    [Parameter(ParameterSetName='RGBColors', Position = 3)]
    [byte]$Blue = 255,
    
    # a horizontal margin to the left and right of the image. Default is 0 (no extra margin)
    [uint16]$MarginHorizontal = 0,
    
    # a vertical margin to the top and bottom of the image. Defaults to 0.
    [uint16]$MarginVertical = 0,
    
    # set suffix that is added to the new file
    # if the suffix is a blank string, the original file is overwritten
    [string]$Suffix = '_w',
    
    # when specified, new SVG file is opened by default app
    [switch]$OpenFile
    
    
  )

  Add-Type -AssemblyName System.Web
  
  $text = Get-Content -Path $Path
  
  # extract viewbox
  [double]$x = 0
  [double]$y = 0
  [double]$width = 0
  [double]$height = 0
  
  $pattern = 'viewBox="(\d{1,5}\.\d{1,5})\s(\d{1,5}\.\d{1,5})\s(\d{1,5}\.\d{1,5})\s(\d{1,5}\.\d{1,5})"'
  if ($text[0] -match $pattern)
  {
    $x = $matches[1]
    $y = $matches[2]
    $width = $matches[3]
    $height = $matches[4]
  }
  else
  {
    throw 'No viewbox found in SVG. SVG must have been created by KiCAD or compatible.'
  }
  
  # if there is a margin, add it to the viewbox
  $x -= $MarginHorizontal
  $y -= $MarginVertical
  $width += (2 * $MarginHorizontal)
  $height += (2 * $MarginVertical)
  
  # create background rectangle
  if ($PSCmdlet.ParameterSetName -eq 'RGBColors')
  {
    $rect = "<rect x=""$x"" y=""$y"" width=""$width"" height=""$height"" fill=""rgb($Red,$Green,$Blue)"" />"
  }
  else
  {
    # make sure a hex value is prepended with '#'
    if ($BackgroundColor.Length -eq 6 -or $BackgroundColor.Length -eq 8)
    {
        # if it is convertible...
        try
        {
          $null = [convert]::ToInt32($BackgroundColor,16)
          # ...then add the prefix:
          $BackgroundColor = '#' + $BackgroundColor
        }
        catch {}
    }
    $rect = "<rect x=""$x"" y=""$y"" width=""$width"" height=""$height"" fill=""$BackgroundColor"" />"    
  }
  
  # add the new rect in line 3:
  $text[2] = $rect
  
  # if a margin was specified, we need to replace the viewbox in line 1, too
  if (($MarginHorizontal -ne 0) -or ($MarginVertical -ne 0))
  {
    $newViewbox = "viewBox=""$x $y $width $height"""
    
    $text[0] = $text[0] -replace $pattern, $newViewbox
    
  }
  
  # adjust the file title
  $filename = [System.Io.Path]::GetFileNameWithoutExtension($Path)
  $filenameEncoded = [System.Web.HttpUtility]::HtmlEncode($filename)
  $text[1] = "<title>$filenameEncoded</title>"
  
  # save adjusted file
  $folder = Split-Path -Path $Path 
  $newFile = Join-Path -Path $folder -ChildPath "${filename}$($suffix.Trim()).svg"
  Set-Content -Path $newFile -Value $text -Encoding UTF8 -Force
  
  if ($OpenFile) { Invoke-Item -Path $newFile }
}
 